#!/usr/bin/env bash

#set -x

VERSION="v0.7.0"
SHORTSHA=$(git rev-parse --short HEAD)
LONGSHA=$(git rev-parse HEAD)

TAG_VERSION=":$VERSION"
TAG_SHORTSHA=":$SHORTSHA"
TAG_LONGSHA=":$LONGSHA"

BUILD_WHEN=$(date)
BUILD_WHEN_UTC=$(date -u +"%Y-%m-%dT%H-%M-%SZ")
COMMENT="hostname: $(hostname), who=$(whoami)"

cat <<EOF_VERSIONS > _versions.env
#                                                   
# This file is generated by build.update-versions.sh
#

VERSION="$VERSION"
SHORTSHA="$SHORTSHA"
LONGSHA="$LONGSHA"

# used to tag docker images when built from docker compose build (via ./build.sh)
TAG_VERSION="$TAG_VERSION"
TAG_SHORTSHA="$TAG_SHORTSHA"
TAG_LONGSHA="$TAG_LONGSHA"

# injected as labels into the docker image
BUILD_WHEN="$BUILD_WHEN"
BUILD_WHEN_UTC="$BUILD_WHEN_UTC"
COMMENT="$COMMENT"
EOF_VERSIONS


